FROM arm64v8/ubuntu

RUN apt-get update
RUN apt-get install -y gcc libudev-dev

COPY Linux/UsbEventWatcher.Linux.c .

COPY entrypoint.sh .
RUN chmod +x entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]

CMD ["arm64", "Release"]