# executed on "docker build":

FROM arm32v7/ubuntu

RUN apt-get update
RUN apt-get install -y gcc libudev-dev

COPY Linux/UsbEventWatcher.Linux.c .

COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

# executed on "docker run":

ENTRYPOINT ["./entrypoint.sh"]

CMD ["arm", "Release"]