# executed on "docker build":

FROM arm64v8/ubuntu

RUN apt-get update
RUN apt-get install -y gcc libudev-dev

COPY Linux/UsbEventWatcher.Linux.c .

COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

RUN gcc -march=armv8-a -shared UsbEventWatcher.Linux.c -o UsbEventWatcher.Linux.so -ludev -fPIC

# executed on "docker run":

ENTRYPOINT ["./entrypoint.sh"]

CMD ["arm64", "Release"]